name: o3d
channels:
  - c4aarch64
  - conda-forge
  - gaiar
  - defaults
  - https://conda.anaconda.org/c4aarch64
  - https://conda.anaconda.org/conda-forge
dependencies:
  - ca-certificates=2018.03.07=0
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hf897c2e_4
  - ld_impl_linux-aarch64=2.39=ha75b1e8_0
  - libffi=3.4.2=h3557bc0_5
  - libgcc-ng=12.2.0=h607ecd0_19
  - libgomp=12.2.0=h607ecd0_19
  - libnsl=2.0.0=hf897c2e_0
  - libsqlite=3.40.0=hf9034f9_0
  - libuuid=2.32.1=hf897c2e_1000
  - libzlib=1.2.13=h4e544f5_4
  - ncurses=6.3=headf329_1
  - openssl=3.0.7=h4e544f5_0
  - pip=22.3.1=pyhd8ed1ab_0
  - python=3.8.13=h92ab765_0_cpython
  - readline=8.1.2=h38e3740_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sqlite=3.40.0=h69ca7e5_0
  - tk=8.6.12=hd8af866_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xz=5.2.6=h9cdd2b7_0
  - pip:
    - attrs==25.3.0
    - blinker==1.8.2
    - certifi==2025.8.3
    - charset-normalizer==3.4.3
    - click==8.1.8
    - configargparse==1.7.1
    - contourpy==1.1.1
    - cycler==0.12.1
    - dash==3.2.0
    - fastjsonschema==2.21.2
    - flask==3.0.3
    - fonttools==4.57.0
    - idna==3.10
    - importlib_metadata==8.5.0
    - importlib_resources==6.4.5
    - itsdangerous==2.2.0
    - jinja2==3.1.6
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter_core==5.8.1
    - kiwisolver==1.4.7
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - narwhals==1.42.1
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - numpy==1.24.4
    - open3d==0.18.0
    - opencv-python==4.12.0.88
    - packaging==25.0
    - pillow==10.4.0
    - pkgutil_resolve_name==1.3.10
    - platformdirs==4.3.6
    - plotly==6.3.0
    - pyparsing==3.1.4
    - pyrealsense2==2.55.1.6486
    - python-dateutil==2.9.0.post0
    - referencing==0.35.1
    - requests==2.32.4
    - retrying==1.4.2
    - rpds-py==0.20.1
    - six==1.17.0
    - traitlets==5.14.3
    - typing_extensions==4.13.2
    - urllib3==2.2.3
    - werkzeug==3.0.6
    - zipp==3.20.2
prefix: /root/archiconda3/envs/o3d

